### ISSUE TITLE
Input vars saved and not queried during subsequent runs of `devspace dev`

### ISSUE THREAD

**Issue by dtardoin** [loft-sh/devspace#1331]
**What happened?**  
The first time I ran `devspace dev`, the input variable correctly asked me for variable contents. The second time, it autopopulated it with the cached response from the first time I ran `devspace dev`

**What did you expect to happen instead?**  
The input variable gets queried every single time I run `devspace dev`

**How can we reproduce the bug?** Run `devspace dev` multiple times with input variables and see that any time after the first, the variable isn't queried.

**Local Environment:**  
- DevSpace Version: 5.8.1
- Operating System: mac
- Deployment method: helm 
**Kubernetes Cluster:**  
- AWS
- Kubernetes Version: 1.18.9
**Anything else we need to know?**  
Not sure if this is really a bug, but this is definitely not the way I'd expect this feature to work, or at least there should be a configuration option to always ask the question.

/kind bug

**Comment by FabianKramm** [comment]
@dtardoin thanks for opening this issue! That is actually intended behaviour as documented here: https://devspace.sh/cli/docs/configuration/variables/basics . You can reset cached variables via the `devspace reset vars` command. Out of curiosity, why do you need to reset the variables every time the user runs `devspace dev`?

**Comment by dtardoin** [comment]
My specific use case is to ask if the user wants to pull a chart out of a registry or use a locally maintained one (in the case that the user is testing a chart update), specifically with predefined options, and this is something that could change every time the user runs `devspace dev`.

**Comment by LukasGentele** [comment]
@FabianKramm how about adding a `cache: true/false` (default: true) option for vars? Or a `ttl: -1 = infinite, 0-x = seconds to cache` ? The ttl could be useful for command-based vars. For anything else, a boolean may be good enough.

**Comment by FabianKramm** [comment]
@LukasGentele currently command variables are not cached and I don't think we actually should cache them, which probably would lead to a lot of unexpected behaviour since caching is not very transparent there and only makes sense in a few use cases at all. Caching of config variables currently only applies to user questions (env vars are also not cached) and I think a `cache: true/false` field would add more confusion than help, since this would imply that you could cache anything.

I guess what we could do is to add a new `source: input_uncached` that would force a question every time and not save the variable in the cache.

**Comment by LukasGentele** [comment]
I get the point about not needing to cache commands but I don't think we should add a separate source for this. That is very confusing and not very deterministic in some cases. Since input is the fallback for env, how would a user be able to disable caching that? What if we want to add the cache for commands later on.. another source? What if a new source would be added later on and that would need caching as well? Adding always source + source_uncached does not seem like good design to me. 

I would suggest to add `cache: true/false` and describe in the docs for which sources this is supported. This allows us to easily add new sources to this cache on/off feature later on if needed. That seems pretty standard practice to me for cases like this one.

**Comment by kuuji** [comment]
> I guess what we could do is to add a new source: input_uncached that would force a question every time and not save the variable in the cache.

I like this a lot and could use it myself. I actually came here to gauge interest for such a thing if I were to contribute it.
I can take a stab at it @FabianKramm unless you already have something in the works.
