### ISSUE TITLE
`--inactivity-timeout` onSleep onLock

### ISSUE THREAD

**Issue by fmc100** [loft-sh/devspace#1351]
**What happened?**  
The `--inactivity-timeout` doesn't work on sleep or on lock of my mac.

**What did you expect to happen instead?**  
I expected the timeout to trigger either immediately after either event or after the time I set for it.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Run `devspace dev --inactivity-timeout 1` then lock or put your machine to sleep and wait 1-2 mins. Once you open your machine up again it will still be running and would have not timed out.

**Local Environment:**  
- DevSpace Version: 5.9.1
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.18.9

**Anything else we need to know?**  
I don't know if devspace should just stop port-forwarding on sleep or lock or if inactivity-timeout should be the one that handles that. Something worth considering.

/kind bug

**Comment by FabianKramm** [comment]
@fmc100 thanks for opening this issue! Yes you are correct, seems like devspace is not picking up sleep correctly on macOS

**Comment by FabianKramm** [comment]
@fmc100 Sorry for the slight delay, we investigated the issue and unfortunately there is no way for us to tell when mac is going to sleep (however DevSpace will not do anything during this time as well). 

If the issue is that devspace does not interrupt active connections to trigger sleep mode of a space in loft, we added a feature for this into loft itself that should solve this issue (see [loft sleep mode docs](https://loft.sh/docs/self-service/sleep-mode#how-to-deal-with-long-running-requests)), where loft will detect idle connections and close them after a certain timeout, which should solve the issue with sleeping macs running devspace.

**Comment by fmc100** [comment]
yeah that should work, thanks!
