### ISSUE TITLE
Apply CRDs first

### ISSUE THREAD

**Issue by fg91** [loft-sh/devspace#1354]
**Is your feature request related to a problem?**  

When devspace deployments contain manifests containing custom resource definitions, these have to be applied first or the respective `devspace deploy` fails.
An example is, for instance, the [Kiali manifest](https://raw.githubusercontent.com/istio/istio/release-1.9/samples/addons/kiali.yaml) of istio. 

For manifests created by the user herself/himself, this is not an issue as they can be separated easily. When using manifests from other providers, they have to be downloaded and manually split into two manifests.

**Which solution do you suggest?** 

As devspace parses the manifest anyway, it could first filter out any CRDs, apply them, and then apply the manifest itself.

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@fg91 thanks for creating this issue! Currently we just call `kubectl create -f manifests.yaml "--dry-run -o yaml` exchange the image names and then call `kubectl apply -f manifests.yaml` to apply them. 

I'm not sure if changing the order of the manifests based on their types might not lead to other issues and is something that we should generally do, because I think that staying as close as possible to the actual `kubectl` behaviour is something that people can rely on and easily debug.

**Comment by fg91** [comment]
Ok, I agree, thanks for the arguments!
