### ISSUE TITLE
imageFlag not working as expected

### ISSUE THREAD

**Issue by sbulman** [loft-sh/devspace#1357]
I have a devspace config file using a custom build. The build tool I am using requires the TAG to be passed using a flag (-Pv) so I defined the following values:

imageFlag: -Pv
imageTagOnly: true

Based on the documentation, I was expecting this to generate a build command with -Pv=$TAG. Instead, the build command generated has the following form -Pv $TAG (no equals)

**Local Environment:**  
- DevSpace Version: 5.9.1
- Operating System: mac
- Deployment method: na

**Kubernetes Cluster:**  
- Cloud Provider: Docker Desktop
- Kubernetes Version: v1.19.7

/kind bug

**Comment by FabianKramm** [comment]
@sbulman thanks for creating this issue! Not sure if I would call this a bug, since passing flags in the form `--flag value` besides `--flag=value` is also [a best practice](https://clig.dev/#arguments-and-flags) and in almost all cases supported. As a workaround you can also create a small script that will rewrite the `-Pv $TAG` internally into `-Pv $TAG`. Out of curiosity, which build tool are you using that does not support this?

**Comment by sbulman** [comment]
@FabianKramm that fair enough, although I certainly thought the documentation suggested that the format imageTag="$TAG" would be used (rather than passing as an argument at the end of the command.

For this case, I am trying to call a gradle task and setting a project property on the command line. Gradle uses the format -Pnameofproperty=whatever.

Thanks for the workaround, I had already done this and it works fine.

**Comment by FabianKramm** [comment]
@sbulman yes you are correct, seems like the documentation is wrong on that. We'll update the documentation.

**Comment by LukasGentele** [comment]
@sbulman Correct me if I am wrong, but I believe that the gradle flag is just -P and that the key=value is the value for this flag and that's why this is not working, no matter how devspace is passing it because you will need property + = + image as value for the flag. I don't think there is another option than a wrapper script or defining a custom command in devspace.yaml as Fabian recommended

**Comment by sbulman** [comment]
@LukasGentele you are correct. No problem, creating a wrapper is find (and useful when using Kind clusters as it can also 'load' the image into the cluster as part of the build). I'll leave it to @FabianKramm to close the issue when the changes to the documentation have been completed. Thanks.

**Comment by FabianKramm** [comment]
@sbulman Documentation is updated now
