### ISSUE TITLE
OnChange for docker builds

### ISSUE THREAD

**Issue by dtomasi** [loft-sh/devspace#1358]
**Is your feature request related to a problem?**  
NO

**Which solution do you suggest?**  
a onChange option for docker image builds

**Which alternative solutions exist?**  
non

**Additional context**  
I don´t think that any additional context is needed her excepting, I love DevSpace! Its awesome! Thank you guys

/kind feature

**Comment by FabianKramm** [comment]
@dtomasi thanks for creating this issue! I'm not exactly sure what you mean by an `onChange` option for docker builds. Should this be similar to the custom build `onChange` option? If yes, I would like to know a little bit about the use case where this is useful and why using `.dockerignore` is not possible in this case.

**Comment by dtomasi** [comment]
@FabianKramm WOW ... Incredible response time ... 
Yes ... this should work in the same way like for custom builds. The reason behind is that we use Multi-Stage Builds in docker. But for specific targets there is no need to rebuild them if there are no changes.

**Comment by FabianKramm** [comment]
@dtomasi thanks, I see! Currently DevSpace already checks for changes within the images context (excluding all rules defined in `.dockerignore`) and only rebuild if something has changed within the docker context. If you are using multi staged builds, the change we want to introduce in #1356 might work for you aswell, because you could exclude files that are not needed in later stages which would speed up the build process itself and also prevent unnecessary rebuilds as well. Do you think this would solve your issue as well?

**Comment by dtomasi** [comment]
Ok. Thanks. I will give it a try. Sounds promising.
