### ISSUE TITLE
Option to avoid sync of certain files.

### ISSUE THREAD

**Issue by sreepathy-tl** [loft-sh/devspace#2385]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Have a configuration file similar to .gitignore file that contains the list of files and folders that are not be synced with the container. Devspace should not sync those files with the container. (_Maybe you can call it ".syncignore"._[😉](https://emojipedia.org/winking-face/))

**Which alternative solutions exist?**  
Nothing I can think about

**Additional context**  
There are situations where we maintain certain additional files in our local development machine that are not to be synced with the container - for instance: text files containing some scratchpad works, .git directory containing git index, helm charts committed along with source code etc. There is no point in watching these files and syncing them with the running container. Adding this option should reduce syncing overhead too.

**Comment by carlmontanari** [comment]
Hey @sreepathy-tl ! 👋 

you can set ignore files in dev space sync blocks with the ‘excludeFile’ list [here in docs](https://www.devspace.sh/docs/configuration/reference#dev-sync-excludeFile) I think/hope this would cover your use case. Probably it would be a bad idea to just automagically ignore things in a gitignore or docker.ignore since that may actually be things you want in your dev container — but with this setting you could have a .devspace.ignore or just point at a gitignore or whatever works for ya!

let us know if that sounds reasonable?

**Comment by sreepathy-tl** [comment]
My bad! I missed out on the collapsed sections in your really awesome documentation. Will go through it completely once again. Thank you @carlmontanari!
