### ISSUE TITLE
make deploy and purge options consistent

### ISSUE THREAD

**Issue by shaunc** [loft-sh/devspace#958]
**Is your feature request related to a problem?**  

Short option "-d" means different things for purge and deploy.

Currently for deploy:
```
     --deployments string     Only deploy a specifc deployment (You can specify multiple deployments comma-separated
  -d, --force-deploy           Forces to (re-)deploy every deployment
```
But for purge
```
 -d, --deployments string     The deployment to delete (You can specify multiple deployments comma-separated, e.g. devspace-default,devspace-database etc
```

**Which solution do you suggest?**  

Use '-d' for short option for deployments for both; for `--force-deploy` short option should be `-f`.

**Which alternative solutions exist?**  

Getting used to the inconsistency? Always using the long options?

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@shaunc thanks for opening this issue! Yes that is true the `devspace purge` command is a little special in this regard and differs from the `devspace dev` and `devspace deploy` commands. I'd rather suggest to rename the `-d` shortcut from the `devspace purge` command or even delete it completely for `devspace purge`, since `-f` for `devspace deploy --force-deploy` could be confusing with `--force-build` and `--force-dependencies`.

**Comment by shaunc** [comment]
hmm... how about `-i --include-dependencies` for all? (can keep long form `--dependencies` for backward compatibility)?

**Comment by FabianKramm** [comment]
@shaunc I'm not exactly sure what you mean with the flag `--include-dependencies`, is it running `--force-deploy`, `--force-build` and `--force-dependencies` together?

**Comment by shaunc** [comment]
What I mean is to have `--include-dependencies` include a specifically specified set of dependencies, rather than all of them, which is the default. (For symmetry one could also add `--exclude-dependencies` to include all but a given list of dependencies. However, that isn't actually going to be useful that often presumably.) Include/exclude specifications for lists are a convention users are probably aware of. Then you wouldn't have to change the `--force-**` at all.

**Comment by FabianKramm** [comment]
@shaunc Okay, maybe I'm getting something wrong here, but I thought this is about the `--deployments` flag?  You can specify individual dependencies via the `--dependency` flag for `devspace deploy` and `devspace purge`. The process how devspace is deploying things is basically like this:
1. For all dependencies (or only the dependencies that are defined via `--dependency`)
  1a. Check if a dependency is cached (Skip this check if `--force-dependencies` is defined)
  1b. If it is cached and was deployed already don't do anything.
  1c. Build dependency images if necessary (Always build images if `--force-build` is defined)
  1d. Deploy dependency deployments if necessary (Always deploy dependency deployments if `--force-deploy` is defined)
2. Build defined images in devspace.yaml if necessary (Always build images if `--force-build` is defined)
3. Deploy all deployments (or only the deployments that are defined via `--deployments`. If a deployment didn't change and you want to force redeployment you can specify this via `--force-deploy`)

So the flags `--force-build` and `--force-deploy` are applied for dependencies as well as deployments in the initially loaded devspace.yaml. How would the `--include-dependencies` flag be different from the `--dependency` flag?

**Comment by shaunc** [comment]
ach -- sorry; yes -- take all my comments above and change `dependency` to `deployment` -- will change for legibility!

**Comment by LukasGentele** [comment]
I don't think we can change the `-d` flag for `devspace deploy` because it is also in `devspace dev` and it is one of the most important flags for many users. A breaking change like this would not be easy. 

I agree that it is inconsistent with `devspace purge` but expecting `-d` as `--force-deploy` for purge makes no sense, so I believe it is not really a danger of getting mixed up. The only option to resolve the inconsistency is to remove the `-d` shortcut for `devspace purge`. To prevent a breaking change right now, we could also deprecate the shortcut first and remove it later in the next major version.

**Comment by shaunc** [comment]
Hmm.. how about adding the `-I`/`--include-deployments` as an alias? It came up for me because when working on the config of a particular deployment I often type `devspace purge -d foo && devspace deploy` ... and when there was another deployment that was in an odd state I didn't want to think about at the moment, I automatically added `devspace purge -d foo && devspace deploy -d foo`, which, it turns out, isn't what I wanted.... If I could do it with all `-i` instead, and then you could phase out the `-d` for purge.

Of course, not a big deal....

**Comment by shaunc** [comment]
Nothing to be done here I guess... thanks for the discussion! Closing.
